
drop table MICHAELBENNIE.AIRPORT;
drop table MICHAELBENNIE.LOCATION;
drop table MICHAELBENNIE.ROADCONDITION;
drop table MICHAELBENNIE.TIME;
drop table MICHAELBENNIE.WEATHER;
drop table MICHAELBENNIE.ACCIDENT;