SELECT
    EXTRACT(YEAR FROM STARTTIME) AS Year,
    EXTRACT(MONTH FROM STARTTIME) AS Month,
    AVG(SEVERITY) AS AverageSeverity
FROM
    MICHAELBENNIE.ACCIDENT
JOIN
    MICHAELBENNIE.TIME
ON
    ACCIDENT.ID = TIME.ACCIDENTID
GROUP BY
    EXTRACT(YEAR FROM STARTTIME),
    EXTRACT(MONTH FROM STARTTIME)
ORDER BY
    Year,
    Month;
