--add constraints for time
ALTER TABLE MICHAELBENNIE.Time ADD CONSTRAINT pk_Time PRIMARY KEY (AccidentID);
ALTER TABLE MICHAELBENNIE.Time ADD CONSTRAINT fk_Time_Accident FOREIGN KEY (AccidentID) REFERENCES Accident(ID);

--add constraints for location
ALTER TABLE MICHAELBENNIE.LOCATION ADD CONSTRAINT pk_Location PRIMARY KEY (StartLatitude, StartLongitude);

--add constraints for RoadCondition
ALTER TABLE MICHAELBENNIE.ROADCONDITION ADD CONSTRAINT pk_RoadCondition PRIMARY KEY (LocStartLatitude, LocStartLongitude);


--add constraint for Weather
ALTER TABLE MICHAELBENNIE.WEATHER ADD CONSTRAINT pk_Weather PRIMARY KEY (AccidentID);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_Temperature CHECK (Temperature BETWEEN -90 AND 150);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_WindSpeed CHECK (WindSpeed BETWEEN 0 AND 400);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_Visibility CHECK (Visibility BETWEEN 0 AND 100);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_Humidity CHECK (Humidity BETWEEN 1 AND 100);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_Pressure CHECK (Pressure BETWEEN 20 AND 50);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_WindChill CHECK (WindChill BETWEEN -110 AND 110);
ALTER TABLE MICHAELBENNIE.Weather ADD CONSTRAINT chk_Precipitation CHECK (Precipitation BETWEEN 0 AND 50);


--Add Indices for faster lookup
CREATE unique INDEX idx_Time_AccidentID ON Time (AccidentID);
