-- Accident table
SELECT * FROM MICHAELBENNIE.ACCIDENT;

-- Time table
SELECT * FROM MICHAELBENNIE.TIME;

-- Weather table
SELECT * FROM "H.ZENG".WEATHER;

-- RoadCondition table
SELECT * FROM "H.ZENG".ROADCONDITION;

-- Location table
SELECT * FROM MICHAELBENNIE.LOCATION;

-- Airport table
SELECT * FROM MICHAELBENNIE.AIRPORT;

-- USCITIES
SELECT * FROM "P.KEEFE".USCities;