-- Accident table
SELECT * FROM MICHAELBENNIE.ACCIDENT;

-- Time table
SELECT * FROM MICHAELBENNIE.TIME;

-- Weather table
SELECT * FROM MICHAELBENNIE.WEATHER;

-- RoadCondition table
SELECT * FROM MICHAELBENNIE.ROADCONDITION;

-- Location table
SELECT * FROM MICHAELBENNIE.LOCATION;

-- Airport table
SELECT * FROM MICHAELBENNIE.AIRPORT;
